//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControlPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cariler
    {
        public Cariler()
        {
            this.HizmetHareketleri = new HashSet<HizmetHareketleri>();
        }
    
        public int Referans { get; set; }
        public string Kod { get; set; }
        public string Unvan { get; set; }
        public string Sehir { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Ilgili1 { get; set; }
        public string Ilgili1_Unvan { get; set; }
        public string Ilgili1_Telefon1 { get; set; }
        public string Ilgili1_Telefon2 { get; set; }
        public string Ilgili2 { get; set; }
        public string Ilgili2_Unvan { get; set; }
        public string Ilgili2_Telefon1 { get; set; }
        public string Ilgili2_Telefon2 { get; set; }
        public string Adres { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> DprtRef { get; set; }
        public string Ilgili1_Email { get; set; }
        public string Ilgili2_Email { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual ICollection<HizmetHareketleri> HizmetHareketleri { get; set; }
    }
}
