//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControlPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMSEYCRMDBEntities : DbContext
    {
        public EMSEYCRMDBEntities()
            : base("name=EMSEYCRMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cariler> Cariler { get; set; }
        public DbSet<Departmanlar> Departmanlar { get; set; }
        public DbSet<HizmetHareketleri> HizmetHareketleri { get; set; }
        public DbSet<Hizmetler> Hizmetler { get; set; }
        public DbSet<IslemHareketleri> IslemHareketleri { get; set; }
        public DbSet<Islemler> Islemler { get; set; }
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<Projeler> Projeler { get; set; }
    }
}
