//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControlPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmetler
    {
        public Hizmetler()
        {
            this.HizmetHareketleri = new HashSet<HizmetHareketleri>();
        }
    
        public int Referans { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> DprtRef { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual ICollection<HizmetHareketleri> HizmetHareketleri { get; set; }
    }
}
