//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControlPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public int Referans { get; set; }
        public Nullable<System.DateTime> PTarih { get; set; }
        public Nullable<int> KullaniciRef { get; set; }
        public Nullable<int> CariRef { get; set; }
        public string Aciklama { get; set; }
        public string Durumu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string EkAciklama { get; set; }
        public Nullable<int> ProjeRef { get; set; }
        public Nullable<int> DprtRef { get; set; }
        public Nullable<int> Ozel { get; set; }
        public Nullable<int> GrvKlc { get; set; }
        public Nullable<int> Grv { get; set; }
    
        public virtual Cariler Cariler { get; set; }
    }
}
