//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControlPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public Kullanicilar()
        {
            this.HizmetHareketleri = new HashSet<HizmetHareketleri>();
        }
    
        public int Referans { get; set; }
        public string Isim { get; set; }
        public Nullable<int> DepartmanRef { get; set; }
        public string Sifre { get; set; }
        public string MailAdres { get; set; }
        public string MailUser { get; set; }
        public string MailPass { get; set; }
        public string MailHost { get; set; }
        public Nullable<int> MailPort { get; set; }
        public string Role { get; set; }
        public string Tel { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual ICollection<HizmetHareketleri> HizmetHareketleri { get; set; }
    }
}
